#!/bin/bash
RED='\033[0;31m'
YEL='\033[1;33m'
BLU='\033[0;34m'
NC='\033[0m'

if [[ $# -eq 0 ]] ; then
    echo -e "No folder specified, linking ${YEL}${PWD}${NC} "
    read -p "Continue (y/n)?" choice
    case "$choice" in
     n|N ) exit 0 ;;
   #  * ) ;; 
    esac
fi
echo ${1:-$(pwd)}


ln -s ${1:-$(pwd)} /home/gkbot/catkin_ws/src/
if [ $? -eq 0 ]; then
    echo -e  "${BLU}Linked${NC} ${YEL}${1:-$(pwd)}${NC}  to ${YEL}/home/gkbot/catkin_ws/src/${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi
